language: python
python:
  - 3.7
install:
  - pip install -r requirements.txt
script:
  - flake8 hook/__init__.py
  - flake8 hook/models.py
  - flake8 hook/forms.py
  - python -m unittest discover hook/test
